POST http://127.0.0.1:3000/search
Accept: application/json
Content-Type: application/json

{
  "filter": "(&(uid=*))",
  "attributes": ["uid"]
}

###
GET http://127.0.0.1:3000/
Accept: application/json

###
GET http://127.0.0.1:3000/api
Accept: application/json